### ISSUE TITLE
Proposal: add a method to return raw payment model

### ISSUE THREAD

**Issue by stealthmode2** [yozian/spgateway#3]
Thanks for this great library, it works great.

Recently, we want to use this library in our payment api service.
But I don't want to print the form got from api, it might be dangerous.
I think would it be great if add a method to return raw payment model with all encode parameters.

My implementation: https://github.com/stealthmode2/spgateway/commit/0c6719857ad98c02c6a070049a86afb949522758

**Comment by yozian** [comment]
Thank you !

Yes, I do agree with that you want the raw model to be dealt with by yourself.
It's welcome to make a PR !

But, I think the form of the payment would not be so dangerous by returning from API.
